dist: bionic
language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn test:e2e

notifications:
  email: false
  slack:
    on_success: always
    on_failure: change
    rooms:
      - secure: o/6EhsZQs04fjuZGZJwXsSdVrRQFT3cLOvUTl/mc+yStiUJ2W9PCdWEg0bftIgQzp5qKsv6fouZEepww5xgt2wXFJxId+1jnNeSpLBJMPyEMz2c5TXeITdVI5qc5Rlo7JE/7t1b+8QhEuFfxlZArK1B/LSXyfbbz6Oe+C4FnVMFVM0+hFhUqKixMElI8PICNuBT8oKsWhPIv0OVEpJcilKOu7yxQT8TMS/w7usZWOXFnHF8e4gRgL2LyvKu/PTpQMXF0sJ77SpQSbBhfJ2t1ikRQvKpmgemOUIqzfR5EuyIJMjjHDENv6wR5BdVbSNTK7r2SgstISuaELqS4VHuKCOdXS/i2CX72Z1bNSySbVja23A7URbIJ4jjO2W0Xpv+2AnMv9jJTGJluhcVl8N67uvWS3tUS5edzUURPTPeH3kMU/8H8yR9kvh8v9+zELXmGgi4iUDxLWXABEOxj2m2JnjjBoUhP/92Fn1E8IDdidSpUGJVlJtJd1KlH0BnHiQ3JfCKAUokivewHgmM75/Ll2b+bz/lHl4s8erDyNskFdB2Xww1sp5f3ktEHOZQZebb5w6k0SeCDU4ca6JpnK3/ltrtWKNv4GLv/ZmfdYQcn1AQjC+Kw/FZPAFhiKq4cqWNr28eiOnDr8sCmkUBkPzeKMzUF5vqitiK8WWYep5sObhM=
