dist: bionic
language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - ~/.cache
    - ~/.sonar/cache

addons:
  sonarcloud:
    organization: vetrosound
    token:
      secure: "42R7F5rVLk8C0O9OCWhiNskEPZYqKTJjoC2h/Rx9b3dznsPMgaGxtVspm9BNDPjcL3m7IqkM59SPreBxh9qcQFOyVsqbCcayMKWjWtx2plbwbyBmW66tRGUWL818OgAsA4uV2xZUvBrJDU/ePqstPRmfMEoTw+B95AlQqeFD5/Bpgy3yG/svk1tR0km3q/sJkL6p9DTLY9OXt+MlzuhxDji/FXmL2ITuk4XzDNtC4FodTukuGvHJD8G3nX7VdOFGjBUykJ0W5CBM/vWzXnp0AxsvvTIqhakGtbEuIt92ZYe2wEqdNlule2F66Vjs7umD/8P3vymO/7dTpR7rBa5+baDZUBNRQ84sltFJkx+m+sgbgyplNZpwSm8ScFsoMBpVxQvWVKdVqFR2wMVrY8Zq9maZ3Wq1Oif8SXrGQXopQyLiffhA0DWKeaVXm2rDizFmYIu4UhT1B4Kctg+Ioi4O6N8MvLI+bjjEtIoHPOcjMVN7WreRr8NVePIoSjuQ1Xbakhd8ihtA6f5T/voVLurY04USE35rrPER+ud1G+7q2MLszQgDOvA3FEdJZWj2499j3fPZCZGVOlz49/Gd5IKShu/GxC4vJrgfmO/CHyt5X7QeFZ1RXMXkOxMV0kPWBFcJ3Sqv5ApCYZ2UFVuvliy3Qc8KC3Ku9wjPBFHHQKv6NJI="

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn test:e2e
  - sonar-scanner

notifications:
  email: false
  slack:
    on_success: always
    on_failure: change
    rooms:
      - secure: o/6EhsZQs04fjuZGZJwXsSdVrRQFT3cLOvUTl/mc+yStiUJ2W9PCdWEg0bftIgQzp5qKsv6fouZEepww5xgt2wXFJxId+1jnNeSpLBJMPyEMz2c5TXeITdVI5qc5Rlo7JE/7t1b+8QhEuFfxlZArK1B/LSXyfbbz6Oe+C4FnVMFVM0+hFhUqKixMElI8PICNuBT8oKsWhPIv0OVEpJcilKOu7yxQT8TMS/w7usZWOXFnHF8e4gRgL2LyvKu/PTpQMXF0sJ77SpQSbBhfJ2t1ikRQvKpmgemOUIqzfR5EuyIJMjjHDENv6wR5BdVbSNTK7r2SgstISuaELqS4VHuKCOdXS/i2CX72Z1bNSySbVja23A7URbIJ4jjO2W0Xpv+2AnMv9jJTGJluhcVl8N67uvWS3tUS5edzUURPTPeH3kMU/8H8yR9kvh8v9+zELXmGgi4iUDxLWXABEOxj2m2JnjjBoUhP/92Fn1E8IDdidSpUGJVlJtJd1KlH0BnHiQ3JfCKAUokivewHgmM75/Ll2b+bz/lHl4s8erDyNskFdB2Xww1sp5f3ktEHOZQZebb5w6k0SeCDU4ca6JpnK3/ltrtWKNv4GLv/ZmfdYQcn1AQjC+Kw/FZPAFhiKq4cqWNr28eiOnDr8sCmkUBkPzeKMzUF5vqitiK8WWYep5sObhM=
